// lib/utils/otp.ts — OTP generation and validation using Supabase whatsapp_messages table
// OTPs are stored in the DB so that any serverless function instance can read them
// (the WhatsApp webhook needs to detect pending OTPs generated by the auth API)

import { createAdminClient } from "@/lib/supabase/admin";

/**
 * Generates a 6-digit OTP for a phone number and stores it in Supabase.
 * Returns the OTP code.
 */
export async function generateOTP(phoneNumber: string): Promise<string> {
  const code = Math.floor(100000 + Math.random() * 900000).toString();
  const expiresAt = new Date(Date.now() + 10 * 60 * 1000).toISOString(); // 10 minutes

  const supabase = createAdminClient();

  // Mark any previous unused OTPs for this phone as expired
  await supabase
    .from("whatsapp_messages")
    .update({ status: "failed" })
    .eq("message_type", "otp")
    .eq("status", "sent")
    .eq("otp_sent", false)
    .like("content", `%${phoneNumber}%`);

  // Look up user by phone (may not exist yet for new users)
  const { data: user } = await supabase
    .from("users")
    .select("id")
    .eq("whatsapp_number", phoneNumber)
    .single();

  // Insert new OTP record
  await supabase.from("whatsapp_messages").insert({
    user_id: user?.id || null,
    direction: "outbound",
    message_type: "otp",
    content: JSON.stringify({ phone: phoneNumber, code }),
    status: "sent",
    expires_at: expiresAt,
    otp_sent: false,
  });

  return code;
}

/**
 * Validates an OTP code for a phone number.
 * Checks the Supabase whatsapp_messages table for a matching, non-expired OTP.
 */
export async function validateOTP(
  phoneNumber: string,
  code: string
): Promise<boolean> {
  const supabase = createAdminClient();

  // Find a valid OTP record for this phone
  const { data: records } = await supabase
    .from("whatsapp_messages")
    .select("id, content, expires_at")
    .eq("message_type", "otp")
    .eq("status", "sent")
    .gt("expires_at", new Date().toISOString())
    .order("created_at", { ascending: false })
    .limit(20);

  if (!records || records.length === 0) return false;

  // Find matching record by phone + code
  const match = records.find((r) => {
    try {
      const parsed = JSON.parse(r.content);
      return parsed.phone === phoneNumber && parsed.code === code;
    } catch {
      return false;
    }
  });

  if (!match) return false;

  // Mark OTP as used
  await supabase
    .from("whatsapp_messages")
    .update({ status: "read" })
    .eq("id", match.id);

  return true;
}

/**
 * Finds a pending (unsent) OTP for a phone number.
 * Used by the WhatsApp bot to detect when a user has a pending OTP.
 * Returns { id, code } if found, null otherwise.
 */
export async function findPendingOTP(
  phoneNumber: string
): Promise<{ id: string; code: string } | null> {
  const supabase = createAdminClient();

  const { data: records } = await supabase
    .from("whatsapp_messages")
    .select("id, content, expires_at")
    .eq("message_type", "otp")
    .eq("status", "sent")
    .eq("otp_sent", false)
    .gt("expires_at", new Date().toISOString())
    .order("created_at", { ascending: false })
    .limit(10);

  if (!records || records.length === 0) return null;

  const match = records.find((r) => {
    try {
      const parsed = JSON.parse(r.content);
      return parsed.phone === phoneNumber;
    } catch {
      return false;
    }
  });

  if (!match) return null;

  try {
    const parsed = JSON.parse(match.content);
    return { id: match.id, code: parsed.code };
  } catch {
    return null;
  }
}

/**
 * Marks an OTP as sent (the bot delivered it to the user via WhatsApp).
 */
export async function markOTPSent(otpId: string): Promise<void> {
  const supabase = createAdminClient();
  await supabase
    .from("whatsapp_messages")
    .update({ otp_sent: true })
    .eq("id", otpId);
}
